=== raml-apis/Elasticsearch/schemas/stats-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "cluster_name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "status" : {
      "type" : "string" ,
      "required" : false
    } ,
    "indices" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "count" : {
          "type" : "number" ,
          "required" : false
        } ,
        "shards" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "total" : {
              "type" : "number" ,
              "required" : false
            } ,
            "primaries" : {
              "type" : "number" ,
              "required" : false
            } ,
            "replication" : {
              "type" : "number" ,
              "required" : false
            } ,
            "index" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "shards" : {
                  "type" : "object" ,
                  "required" : false ,
                  "properties" : {
                    "min" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "max" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "avg" : {
                      "type" : "number" ,
                      "required" : false
                    }
                  }
                } ,
                "primaries" : {
                  "type" : "object" ,
                  "required" : false ,
                  "properties" : {
                    "min" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "max" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "avg" : {
                      "type" : "number" ,
                      "required" : false
                    }
                  }
                } ,
                "replication" : {
                  "type" : "object" ,
                  "required" : false ,
                  "properties" : {
                    "min" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "max" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "avg" : {
                      "type" : "number" ,
                      "required" : false
                    }
                  }
                }
              }
            }
          }
        } ,
        "docs" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "count" : {
              "type" : "number" ,
              "required" : false
            } ,
            "deleted" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } ,
        "store" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "size" : {
              "type" : "string" ,
              "required" : false
            } ,
            "size_in_bytes" : {
              "type" : "number" ,
              "required" : false
            } ,
            "throttle_time" : {
              "type" : "string" ,
              "required" : false
            } ,
            "throttle_time_in_millis" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } ,
        "fielddata" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "memory_size" : {
              "type" : "string" ,
              "required" : false
            } ,
            "memory_size_in_bytes" : {
              "type" : "number" ,
              "required" : false
            } ,
            "evictions" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } ,
        "filter_cache" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "memory_size" : {
              "type" : "string" ,
              "required" : false
            } ,
            "memory_size_in_bytes" : {
              "type" : "number" ,
              "required" : false
            } ,
            "evictions" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } ,
        "id_cache" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "memory_size" : {
              "type" : "string" ,
              "required" : false
            } ,
            "memory_size_in_bytes" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } ,
        "completion" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "size" : {
              "type" : "string" ,
              "required" : false
            } ,
            "size_in_bytes" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } ,
        "segments" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "count" : {
              "type" : "number" ,
              "required" : false
            }
          }
        }
      }
    } ,
    "nodes" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "count" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "total" : {
              "type" : "number" ,
              "required" : false
            } ,
            "master_only" : {
              "type" : "number" ,
              "required" : false
            } ,
            "data_only" : {
              "type" : "number" ,
              "required" : false
            } ,
            "master_data" : {
              "type" : "number" ,
              "required" : false
            } ,
            "client" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } ,
        "versions" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "string"
            }
          ]
        } ,
        "os" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "available_processors" : {
              "type" : "number" ,
              "required" : false
            } ,
            "mem" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "total" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "total_in_bytes" : {
                  "type" : "number" ,
                  "required" : false
                }
              }
            } ,
            "cpu" : {
              "type" : "array" ,
              "required" : false ,
              "items" : [
                {
                  "type" : "object" ,
                  "properties" : {
                    "vendor" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "model" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "mhz" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "total_cores" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "total_sockets" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "cores_per_socket" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "cache_size" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "cache_size_in_bytes" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "count" : {
                      "type" : "number" ,
                      "required" : false
                    }
                  }
                }
              ]
            }
          }
        } ,
        "process" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "cpu" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "percent" : {
                  "type" : "number" ,
                  "required" : false
                }
              }
            } ,
            "open_file_descriptors" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "min" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "max" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "avg" : {
                  "type" : "number" ,
                  "required" : false
                }
              }
            }
          }
        } ,
        "jvm" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "max_uptime" : {
              "type" : "string" ,
              "required" : false
            } ,
            "max_uptime_in_millis" : {
              "type" : "number" ,
              "required" : false
            } ,
            "version" : {
              "type" : "array" ,
              "required" : false ,
              "items" : [
                {
                  "type" : "object" ,
                  "properties" : {
                    "version" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "vm_name" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "vm_version" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "vm_vendor" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "count" : {
                      "type" : "number" ,
                      "required" : false
                    }
                  }
                }
              ]
            } ,
            "mem" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "heap_used" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "heap_used_in_bytes" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "heap_max" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "heap_max_in_bytes" : {
                  "type" : "number" ,
                  "required" : false
                }
              }
            } ,
            "threads" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } ,
        "fs" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "total" : {
              "type" : "string" ,
              "required" : false
            } ,
            "total_in_bytes" : {
              "type" : "number" ,
              "required" : false
            } ,
            "free" : {
              "type" : "string" ,
              "required" : false
            } ,
            "free_in_bytes" : {
              "type" : "number" ,
              "required" : false
            } ,
            "available" : {
              "type" : "string" ,
              "required" : false
            } ,
            "available_in_bytes" : {
              "type" : "number" ,
              "required" : false
            } ,
            "disk_reads" : {
              "type" : "number" ,
              "required" : false
            } ,
            "disk_writes" : {
              "type" : "number" ,
              "required" : false
            } ,
            "disk_io_op" : {
              "type" : "number" ,
              "required" : false
            } ,
            "disk_read_size" : {
              "type" : "string" ,
              "required" : false
            } ,
            "disk_read_size_in_bytes" : {
              "type" : "number" ,
              "required" : false
            } ,
            "disk_write_size" : {
              "type" : "string" ,
              "required" : false
            } ,
            "disk_write_size_in_bytes" : {
              "type" : "number" ,
              "required" : false
            } ,
            "disk_io_size" : {
              "type" : "string" ,
              "required" : false
            } ,
            "disk_io_size_in_bytes" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } ,
        "plugins" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "name" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "description" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "url" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "jvm" : {
                  "type" : "boolean" ,
                  "required" : false
                } ,
                "site" : {
                  "type" : "boolean" ,
                  "required" : false
                }
              }
            }
          ]
        }
      }
    }
  }
}

=== raml-apis/Elasticsearch/examples/stats-example.json
{
  "cluster_name" : "elasticsearch" ,
  "status" : "green" ,
  "indices" : {
    "count" : 3 ,
    "shards" : {
      "total" : 35 ,
      "primaries" : 15 ,
      "replication" : 1.333333333333333 ,
      "index" : {
        "shards" : {
          "min" : 10 ,
          "max" : 15 ,
          "avg" : 11.66666666666666
        } ,
        "primaries" : {
          "min" : 5 ,
          "max" : 5 ,
          "avg" : 5
        } ,
        "replication" : {
          "min" : 1 ,
          "max" : 2 ,
          "avg" : 1.3333333333333333
        }
      }
    } ,
    "docs" : {
      "count" : 2 ,
      "deleted" : 0
    } ,
    "store" : {
      "size" : "5.6kb" ,
      "size_in_bytes" : 5770 ,
      "throttle_time" : "0s" ,
      "throttle_time_in_millis" : 0
    } ,
    "fielddata" : {
      "memory_size" : "0b" ,
      "memory_size_in_bytes" : 0 ,
      "evictions" : 0
    } ,
    "filter_cache" : {
      "memory_size" : "0b" ,
      "memory_size_in_bytes" : 0 ,
      "evictions" : 0
    } ,
    "id_cache" : {
      "memory_size" : "0b" ,
      "memory_size_in_bytes" : 0
    } ,
    "completion" : {
      "size" : "0b" ,
      "size_in_bytes" : 0
    } ,
    "segments" : {
      "count" : 2
    }
  } ,
  "nodes" : {
    "count" : {
      "total" : 2 ,
      "master_only" : 0 ,
      "data_only" : 0 ,
      "master_data" : 2 ,
      "client" : 0
    } ,
    "versions" : [
      "0.90.8"
    ] ,
    "os" : {
      "available_processors" : 4 ,
      "mem" : {
        "total" : "8gb" ,
        "total_in_bytes" : 8589934592
      } ,
      "cpu" : [
        {
          "vendor" : "Intel" ,
          "model" : "MacBookAir5,2" ,
          "mhz" : 2000 ,
          "total_cores" : 4 ,
          "total_sockets" : 4 ,
          "cores_per_socket" : 16 ,
          "cache_size" : "256b" ,
          "cache_size_in_bytes" : 256 ,
          "count" : 1
        }
      ]
    } ,
    "process" : {
      "cpu" : {
        "percent" : 3
      } ,
      "open_file_descriptors" : {
        "min" : 200 ,
        "max" : 346 ,
        "avg" : 273
      }
    } ,
    "jvm" : {
      "max_uptime" : "24s" ,
      "max_uptime_in_millis" : 24054 ,
      "version" : [
        {
          "version" : "1.6.0_45" ,
          "vm_name" : "Java HotSpot(TM) 64-Bit Server VM" ,
          "vm_version" : "20.45-b01-451" ,
          "vm_vendor" : "Apple Inc." ,
          "count" : 2
        }
      ] ,
      "mem" : {
        "heap_used" : "38.3mb" ,
        "heap_used_in_bytes" : 40237120 ,
        "heap_max" : "1.9gb" ,
        "heap_max_in_bytes" : 2130051072
      } ,
      "threads" : 89
    } ,
    "fs" : {
      "total" : "232.9gb" ,
      "total_in_bytes" : 250140434432 ,
      "free" : "31.3gb" ,
      "free_in_bytes" : 33705881600 ,
      "available" : "31.1gb" ,
      "available_in_bytes" : 33443737600 ,
      "disk_reads" : 21202753 ,
      "disk_writes" : 27028840 ,
      "disk_io_op" : 48231593 ,
      "disk_read_size" : "528gb" ,
      "disk_read_size_in_bytes" : 566980806656 ,
      "disk_write_size" : "617.9gb" ,
      "disk_write_size_in_bytes" : 663525366784 ,
      "disk_io_size" : "1145.9gb" ,
      "disk_io_size_in_bytes" : 1230506173440
    } ,
    "plugins" : [
      {
        "name" : "inquisitor" ,
        "description" : "" ,
        "url" : "/_plugin/inquisitor/" ,
        "jvm" : false ,
        "site" : true
      }
    ]
  }
}
