=== raml-apis/Elasticsearch/schemas/termVectors-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "_index" : {
      "type" : "string" ,
      "required" : false
    } ,
    "_type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "_version" : {
      "type" : "number" ,
      "required" : false
    } ,
    "found" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "term_vectors" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "text" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "field_statistics" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "doc_count" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "sum_doc_freq" : {
                  "type" : "number" ,
                  "required" : false
                } ,
                "sum_ttf" : {
                  "type" : "number" ,
                  "required" : false
                }
              }
            } ,
            "terms" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "test" : {
                  "type" : "object" ,
                  "required" : false ,
                  "properties" : {
                    "doc_freq" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "term_freq" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "tokens" : {
                      "type" : "array" ,
                      "required" : false ,
                      "items" : [
                        {
                          "type" : "object" ,
                          "properties" : {
                            "end_offset" : {
                              "type" : "number" ,
                              "required" : false
                            } ,
                            "payload" : {
                              "type" : "string" ,
                              "required" : false
                            } ,
                            "position" : {
                              "type" : "number" ,
                              "required" : false
                            } ,
                            "start_offset" : {
                              "type" : "number" ,
                              "required" : false
                            }
                          }
                        }
                      ]
                    } ,
                    "ttf" : {
                      "type" : "number" ,
                      "required" : false
                    }
                  }
                } ,
                "twitter" : {
                  "type" : "object" ,
                  "required" : false ,
                  "properties" : {
                    "doc_freq" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "term_freq" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "tokens" : {
                      "type" : "array" ,
                      "required" : false ,
                      "items" : [
                        {
                          "type" : "object" ,
                          "properties" : {
                            "end_offset" : {
                              "type" : "number" ,
                              "required" : false
                            } ,
                            "payload" : {
                              "type" : "string" ,
                              "required" : false
                            } ,
                            "position" : {
                              "type" : "number" ,
                              "required" : false
                            } ,
                            "start_offset" : {
                              "type" : "number" ,
                              "required" : false
                            }
                          }
                        }
                      ]
                    } ,
                    "ttf" : {
                      "type" : "number" ,
                      "required" : false
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== raml-apis/Elasticsearch/examples/termVectors-example.json
{
  "_id" : "1" ,
  "_index" : "twitter" ,
  "_type" : "tweet" ,
  "_version" : 1 ,
  "found" : true ,
  "term_vectors" : {
    "text" : {
      "field_statistics" : {
        "doc_count" : 2 ,
        "sum_doc_freq" : 6 ,
        "sum_ttf" : 8
      } ,
      "terms" : {
        "test" : {
          "doc_freq" : 2 ,
          "term_freq" : 3 ,
          "tokens" : [
            {
              "end_offset" : 12 ,
              "payload" : "d29yZA==" ,
              "position" : 1 ,
              "start_offset" : 8
            } , {
              "end_offset" : 17 ,
              "payload" : "d29yZA==" ,
              "position" : 2 ,
              "start_offset" : 13
            } , {
              "end_offset" : 22 ,
              "payload" : "d29yZA==" ,
              "position" : 3 ,
              "start_offset" : 18
            }
          ] ,
          "ttf" : 4
        } ,
        "twitter" : {
          "doc_freq" : 2 ,
          "term_freq" : 1 ,
          "tokens" : [
            {
              "end_offset" : 7 ,
              "payload" : "d29yZA==" ,
              "position" : 0 ,
              "start_offset" : 0
            }
          ] ,
          "ttf" : 2
        }
      }
    }
  }
}
